services:
  chat:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: chatuser
      DB_PASSWORD: ch@tpass
      DB_NAME: chatdb
    command: ["bash", "./scripts/wait-for-db.sh", "db:3306", "-t", "60", "--", "npm", "start"]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: ch@tpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
