name: Testy aplikacji

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Zainstaluj Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalacja zależności
        run: npm install

      - name: Uruchom testy
        run: npm test
